apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - name: api
              containerPort: 8080
            - name: logs
              containerPort: 8081
            - name: soap
              containerPort: 8082

          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          # Enable these to simulate the app running (disable the spring.profiles args and probes)
          #command: [ "/bin/sh", "-c", "--" ]
          #args: [ "while true; do sleep 30; done;" ]
          args:
            - "--spring.profiles.active={ .Values.env }"

          lifecycle:
            preStop:
              exec:
                command: [ "wget", "http://localhost:8080/service/shutdown" ]

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"

          # Disable these if testing the app
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          # Disable these if testing the app
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          volumeMounts:
            - mountPath: /app
              name: config
      volumes:
        - name: config
          configMap:
            name: {{ .Values.name }}-config
            items:
              - key: config.json
                path: config.json