# Default values
replicaCount: 1
namespace: inpost-default
name: test
image:
  repository: busybox
  tag: stable
service:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: api
    - port: 8081
      targetPort: 8081
      name: logs
    - port: 8082
      targetPort: 8082
      name: soap
ingress:
  hosts: []
secret:
  username: ""
  password: ""
